FROM node:24.16.0-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --omit=dev

COPY . ./

RUN npm run build

FROM node:24.16.0-alpine
WORKDIR /app

COPY --from=build /app/.output/ ./

ENV PORT=80
ENV HOST=0.0.0.0

EXPOSE 80

CMD ["node", "server/index.mjs"]